import * as i from 'types';

const realms: i.Realms = {
  eu: {
    english: [
      'Amnennar',
      'Ashbringer',
      'Auberdine',
      'Bloodfang',
      'Celebras',
      "Dragon's Call",
      'Dragonfang',
      'Dreadmist',
      'Earthshaker',
      'Everlook',
      'Finkle',
      'Firemaw',
      'Flamelash',
      'Gandling',
      'Gehennas',
      'Giantstalker',
      'Golemagg',
      'Heartstriker',
      'Hydraxian Waterlords',
      "Jin'do",
      'Judgement',
      'Lakeshire',
      'Lucifron',
      'Mandokir',
      'Mirage Raceway',
      'Mograine',
      'Nethergarde Keep',
      'Noggenfogger',
      'Patchwerk',
      'Pyrewood Village',
      'Razorfen',
      'Razorgore',
      'Shazzrah',
      'Skullflame',
      'Stitches',
      "Nek'Rosh",
      'Stonespine',
      'Sulfuron',
      'Ten Storms',
      'Thekal',
      'Transcendence',
      'Venoxis',
      'Zandalar Tribe',
    ],
    russian: [
      {
        russian: 'Вестник Рока',
        english: 'Doomsayer',
      },
      {
        russian: 'Змейталак',
        english: 'Wyrmthalak',
      },
      {
        russian: 'Пламегор',
        english: 'Flamegor',
      },
      {
        russian: 'Рок-Делар',
        english: 'Rhokdelar',
      },
      {
        russian: 'Хроми',
        english: 'Chromie',
      },
    ],
  },
  us: [
    'Anathema',
    'Angerforge',
    'Arcanite Reaper',
    'Arugal',
    'Ashkandi',
    'Atiesh',
    'Azuresong',
    'Benediction',
    'Bigglesworth',
    'Blaumeux',
    'Bloodsail Buccaneers',
    'Deviate Delight',
    'Earthfury',
    'Eranikus',
    'Faerlina',
    'Fairbanks',
    'Felstriker',
    'Grobbulus',
    'Heartseeker',
    'Herod',
    'Incendius',
    'Kirtonos',
    'Kromcrush',
    'Kurinnaxx',
    'Loatheb',
    'Maladath',
    'Mankrik',
    'Myzrael',
    'Netherwind',
    'Old Blanchy',
    'Pagle',
    'Rattlegore',
    'Remulos',
    'Skeram',
    'Skyfury',
    'Smolderweb',
    'Stalagg',
    "Sul'thraze",
    'Sulfuras',
    'Thalnos',
    'Thunderfury',
    'Westfall',
    'Whitemane',
    'Windseeker',
    'Yojamba',
  ],
};

export default realms;
