DELETE FROM sqlite_sequence WHERE name = 'realms';
DELETE FROM "realms";
INSERT INTO "realms" ("id", "name", "version", "region", "tag") VALUES
(0, 'stitches', 'era', 'eu', 'hardcore'),
(1, 'nek''rosh', 'era', 'eu', 'hardcore'),
(2, 'Amnennar', 'classic', 'eu', 'normal'),
(3, 'Ashbringer', 'classic', 'eu', 'normal'),
(4, 'Auberdine', 'classic', 'eu', 'normal'),
(5, 'Bloodfang', 'classic', 'eu', 'normal'),
(6, 'Celebras', 'classic', 'eu', 'normal'),
(7, "Dragon's Call", 'classic', 'eu', 'normal'),
(8, 'Dragonfang', 'classic', 'eu', 'normal'),
(9, 'Dreadmist', 'classic', 'eu', 'normal'),
(10, 'Earthshaker', 'classic', 'eu', 'normal'),
(11, 'Everlook', 'classic', 'eu', 'normal'),
(12, 'Finkle', 'classic', 'eu', 'normal'),
(13, 'Firemaw', 'classic', 'eu', 'normal'),
(14, 'Flamelash', 'classic', 'eu', 'normal'),
(15, 'Gandling', 'classic', 'eu', 'normal'),
(16, 'Gehennas', 'classic', 'eu', 'normal'),
(17, 'Giantstalker', 'classic', 'eu', 'normal'),
(18, 'Golemagg', 'classic', 'eu', 'normal'),
(19, 'Heartstriker', 'classic', 'eu', 'normal'),
(20, 'Hydraxian Waterlords', 'classic', 'eu', 'normal'),
(21, "Jin'do", 'classic', 'eu', 'normal'),
(22, 'Judgement', 'classic', 'eu', 'normal'),
(23, 'Lakeshire', 'classic', 'eu', 'normal'),
(24, 'Lucifron', 'classic', 'eu', 'normal'),
(25, 'Mandokir', 'classic', 'eu', 'normal'),
(26, 'Mirage Raceway', 'classic', 'eu', 'normal'),
(27, 'Mograine', 'classic', 'eu', 'normal'),
(28, 'Nethergarde Keep', 'classic', 'eu', 'normal'),
(29, 'Noggenfogger', 'classic', 'eu', 'normal'),
(30, 'Patchwerk', 'classic', 'eu', 'normal'),
(31, 'Pyrewood Village', 'classic', 'eu', 'normal'),
(32, 'Razorfen', 'classic', 'eu', 'normal'),
(33, 'Razorgore', 'classic', 'eu', 'normal'),
(34, 'Shazzrah', 'classic', 'eu', 'normal'),
(35, 'Skullflame', 'classic', 'eu', 'normal'),
(36, 'Stonespine', 'classic', 'eu', 'normal'),
(37, 'Sulfuron', 'classic', 'eu', 'normal'),
(38, 'Ten Storms', 'classic', 'eu', 'normal'),
(39, 'Thekal', 'classic', 'eu', 'normal'),
(40, 'Transcendence', 'classic', 'eu', 'normal'),
(41, 'Venoxis', 'classic', 'eu', 'normal'),
(42, 'Zandalar Tribe', 'classic', 'eu', 'normal'),
(43, 'Anathema', 'classic', 'us', 'normal'),
(44, 'Angerforge', 'classic', 'us', 'normal'),
(45, 'Arcanite Reaper', 'classic', 'us', 'normal'),
(46, 'Arugal', 'classic', 'us', 'normal'),
(47, 'Ashkandi', 'classic', 'us', 'normal'),
(48, 'Atiesh', 'classic', 'us', 'normal'),
(49, 'Azuresong', 'classic', 'us', 'normal'),
(50, 'Benediction', 'classic', 'us', 'normal'),
(51, 'Bigglesworth', 'classic', 'us', 'normal'),
(52, 'Blaumeux', 'classic', 'us', 'normal'),
(53, 'Bloodsail Buccaneers', 'classic', 'us', 'normal'),
(54, 'Deviate Delight', 'classic', 'us', 'normal'),
(55, 'Earthfury', 'classic', 'us', 'normal'),
(56, 'Eranikus', 'classic', 'us', 'normal'),
(57, 'Faerlina', 'classic', 'us', 'normal'),
(58, 'Fairbanks', 'classic', 'us', 'normal'),
(59, 'Felstriker', 'classic', 'us', 'normal'),
(60, 'Grobbulus', 'classic', 'us', 'normal'),
(61, 'Heartseeker', 'classic', 'us', 'normal'),
(62, 'Herod', 'classic', 'us', 'normal'),
(63, 'Incendius', 'classic', 'us', 'normal'),
(64, 'Kirtonos', 'classic', 'us', 'normal'),
(65, 'Kromcrush', 'classic', 'us', 'normal'),
(66, 'Kurinnaxx', 'classic', 'us', 'normal'),
(67, 'Loatheb', 'classic', 'us', 'normal'),
(68, 'Maladath', 'classic', 'us', 'normal'),
(69, 'Mankrik', 'classic', 'us', 'normal'),
(70, 'Myzrael', 'classic', 'us', 'normal'),
(71, 'Netherwind', 'classic', 'us', 'normal'),
(72, 'Old Blanchy', 'classic', 'us', 'normal'),
(73, 'Pagle', 'classic', 'us', 'normal'),
(74, 'Rattlegore', 'classic', 'us', 'normal'),
(75, 'Remulos', 'classic', 'us', 'normal'),
(76, 'Skeram', 'classic', 'us', 'normal'),
(77, 'Skyfury', 'classic', 'us', 'normal'),
(78, 'Smolderweb', 'classic', 'us', 'normal'),
(79, 'Stalagg', 'classic', 'us', 'normal'),
(80, "Sul'thraze", 'classic', 'us', 'normal'),
(81, 'Sulfuras', 'classic', 'us', 'normal'),
(82, 'Thalnos', 'classic', 'us', 'normal'),
(83, 'Thunderfury', 'classic', 'us', 'normal'),
(84, 'Westfall', 'classic', 'us', 'normal'),
(85, 'Whitemane', 'classic', 'us', 'normal'),
(86, 'Windseeker', 'classic', 'us', 'normal'),
(87, 'Yojamba', 'classic', 'us', 'normal'),
(88, 'Firemaw', 'era', 'eu', 'era');
