// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/item/[...item]": InferRoute<import("./src/app/item/[...item]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/": StaticRoute;
  }
}
