name: CD Vercel Edge Api

on:
  push:
    branches: '*'
    paths:
      - vercel/**
  pull_request:
    branches: '*'
    paths:
      - vercel/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout to branch to execute from
      - name: Checkout Branch
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # vercel pull doesnt work for some reason
      - name: Setup Vercel files
        run: |
          cd vercel
          mkdir -p .vercel
          touch project.json
          echo $'{ "projectId": "${{ secrets.VERCEL_API_PROJECT_ID }}", "orgId": "${{ secrets.VERCEL_API_ORG_ID }}", "settings": { "createdAt": 1658573033947, "framework": null, "devCommand": null, "installCommand": null, "buildCommand": null, "outputDirectory": null, "rootDirectory": null, "directoryListing": false, "nodeVersion": "16.x" } }' > .vercel/project.json

      - name: Deploy to Vercel
        run: |
          cd vercel
          pnpm vercel deploy ${{ github.ref == 'refs/heads/master' && '--prod' || '' }} --token ${{ secrets.VERCEL_TOKEN }}
