name: CI

# Run this on every push and pull
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout to branch to execute from
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      # ci / ignore-scripts speeds this step up a lot
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Build monorepo
        run: yarn build -- --cwd=. --graph
