name: CI

# Run this on every push and pull
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout to branch to execute from
      - uses: actions/checkout@v2

      # Setup pnpm
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x.x
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      # Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: npm run build -- --cwd=. --graph
        