name: CI

# Run this on every push and pull
on:
  pull_request:
    branches: '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout to branch to execute from
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: |
          cd apps/extension
          bun run tc
          cd ../..

      - name: Build monorepo
        run: bun run build
