name: Deploy to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: |
          bun run build
          cd apps/extension
          bun run ci:create-dist
          cd ../..

      - name: Deploy to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: apps/extension/auctionoton.zip
          extension-id: ${{ secrets.CHROME_WEBSTORE_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
